### ISSUE TITLE
mobile and ipad mini screen sizes legend covers popup

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Geologic-Index-Maps#8]
On an ipad mini screen and smaller, the layer legend coves the popup completely. Maybe we need to add a legend toggle button or just take the legend out on smaller screen sizes?

**Comment by marshallrobinson** [comment]
I used CSS to set "display: none !important" whenever the screen width is less than 755px. I couldn't figure out a way to make the legend show AND show the popups.
